# Site settings
title: "LatinX in AI"
description: "Creating Harmony and Opportunity for Latinx in AI"
# baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "www.latinxinai.org"

# User settings
username: LatinX in AI
user_description: Creating Harmony and Opportunity for Latinx in AI
user_title: Coalition
email: latinxinai@accel.ai
twitter_username: _LXAI
github_username: latinxinai


# Google-analytics
google-analytics:
  id: ""

include: ['_pages']

exclude: ['package.json', 'src' , 'node_modules']
